---
- name: Bootstraps a fresh EC2 instance with EFS and GitLab with CI
  hosts: all
  connection: local
  gather_facts: True
  roles: []
  tasks:
    # TODO: mount efs
    - name: ensure nfs utils are installed
      package: name=nfs-utils
      when: 'efs_url != ""'

    - name: create efs mountpoint
      file:
        path: '{{ efs_mountpoint }}'
        state: 'directory'
        owner: root
        group: root
        mode: '0755'
      when: 'efs_url != ""'

    - name: mount efs
      mount:
        path: '{{ efs_mountpoint }}'
        src: '{{ efs_url }}:/'
        opts: 'nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,_netdev'
        fstype: 'nfs4'
        state: mounted
      when: 'efs_url != ""'

    - include_role: name=inhumantsar.docker-compose-gitlab
